services:
  - type: web
    name: triviapay-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
    autoDeploy: true 