services:
  - type: web
    name: triviapay-backend
    env: python
    buildCommand: pip install -r requirements.txt --no-dev
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
      - key: TESTING
        value: false
      - key: SKIP_TESTS
        value: true
    autoDeploy: true 