"""auth_migration6

Revision ID: 05ecb89850c2
Revises: 1c364de0645f
Create Date: 2025-03-23 22:42:20.403780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ecb89850c2'
down_revision: Union[str, None] = '1c364de0645f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('status_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'status_flag')
    # ### end Alembic commands ###
