"""add_sub_to_users

Revision ID: 3f451daf1184
Revises: bf4a92051db7
Create Date: 2025-03-26 00:00:27.741948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f451daf1184'
down_revision: Union[str, None] = 'bf4a92051db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub', sa.String(), nullable=True, unique=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sub')
    # ### end Alembic commands ###
