"""auth_migration14

Revision ID: 401e39224213
Revises: 444223423368
Create Date: 2025-04-11 19:40:23.814629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '401e39224213'
down_revision: Union[str, None] = '444223423368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_draw_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('custom_winner_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trivia_draw_config_id'), 'trivia_draw_config', ['id'], unique=False)
    op.create_table('trivia_draw_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trivia_draw_winners_id'), 'trivia_draw_winners', ['id'], unique=False)
    op.drop_index('ix_daily_winners_id', table_name='daily_winners')
    op.drop_table('daily_winners')
    op.drop_index('ix_winner_config_id', table_name='winner_config')
    op.drop_table('winner_config')
    op.drop_index('ix_draw_config_id', table_name='draw_config')
    op.drop_table('draw_config')
    op.drop_index('ix_draw_entries_id', table_name='draw_entries')
    op.drop_table('draw_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('draw_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_eligible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='draw_entries_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='draw_entries_pkey')
    )
    op.create_index('ix_draw_entries_id', 'draw_entries', ['id'], unique=False)
    op.create_table('draw_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_custom', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_winner_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='draw_config_pkey')
    )
    op.create_index('ix_draw_config_id', 'draw_config', ['id'], unique=False)
    op.create_table('winner_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manual_winner_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='winner_config_pkey')
    )
    op.create_index('ix_winner_config_id', 'winner_config', ['id'], unique=False)
    op.create_table('daily_winners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('prize_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('draw_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='daily_winners_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_winners_pkey')
    )
    op.create_index('ix_daily_winners_id', 'daily_winners', ['id'], unique=False)
    op.drop_index(op.f('ix_trivia_draw_winners_id'), table_name='trivia_draw_winners')
    op.drop_table('trivia_draw_winners')
    op.drop_index(op.f('ix_trivia_draw_config_id'), table_name='trivia_draw_config')
    op.drop_table('trivia_draw_config')
    # ### end Alembic commands ###
