"""auth_migration13

Revision ID: 444223423368
Revises: 82a840abef60
Create Date: 2025-04-11 19:27:17.964069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '444223423368'
down_revision: Union[str, None] = '82a840abef60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_draw_entries_id'), 'draw_entries', ['id'], unique=False)
    op.drop_index('ix_weekly_winners_id', table_name='weekly_winners')
    op.drop_table('weekly_winners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_winners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('prize_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='weekly_winners_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weekly_winners_pkey')
    )
    op.create_index('ix_weekly_winners_id', 'weekly_winners', ['id'], unique=False)
    op.drop_index(op.f('ix_draw_entries_id'), table_name='draw_entries')
    op.drop_table('draw_entries')
    # ### end Alembic commands ###
