"""remove_trivia_questions_answers_table

Revision ID: 49e732d2545c
Revises: f5e6f9488c47
Create Date: 2025-10-15 19:57:06.347670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49e732d2545c'
down_revision: Union[str, None] = 'f5e6f9488c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trivia_questions_answers_id', table_name='trivia_questions_answers')
    op.drop_table('trivia_questions_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_questions_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('question_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='user_question_answers_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_question_answers_pkey')
    )
    op.create_index('ix_trivia_questions_answers_id', 'trivia_questions_answers', ['id'], unique=False)
    # ### end Alembic commands ###
