"""auth_migration6

Revision ID: 628703cb03fc
Revises: f7b0a00dbc04
Create Date: 2025-03-29 21:52:13.849530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628703cb03fc'
down_revision: Union[str, None] = 'f7b0a00dbc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('was_changed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.ForeignKeyConstraint(['question_number'], ['trivia.question_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_questions_id'), 'daily_questions', ['id'], unique=False)
    op.alter_column('users', 'gems',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'streaks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'lifeline_changes_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lifeline_changes_remaining',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('users', 'streaks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'gems',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_daily_questions_id'), table_name='daily_questions')
    op.drop_table('daily_questions')
    # ### end Alembic commands ###
