"""auth_migration3

Revision ID: 7f0fe0f7f827
Revises: f1c8af27e1f3
Create Date: 2025-03-23 17:21:50.525163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0fe0f7f827'
down_revision: Union[str, None] = 'f1c8af27e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'ssn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'ssn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
