"""auth_migration12

Revision ID: 82a840abef60
Revises: ef6ea108672f
Create Date: 2025-04-11 18:59:09.584827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a840abef60'
down_revision: Union[str, None] = 'ef6ea108672f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('custom_winner_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draw_config_id'), 'draw_config', ['id'], unique=False)
    op.create_table('daily_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_winners_id'), 'daily_winners', ['id'], unique=False)
    op.create_table('weekly_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('prize_amount', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_winners_id'), 'weekly_winners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_winners_id'), table_name='weekly_winners')
    op.drop_table('weekly_winners')
    op.drop_index(op.f('ix_daily_winners_id'), table_name='daily_winners')
    op.drop_table('daily_winners')
    op.drop_index(op.f('ix_draw_config_id'), table_name='draw_config')
    op.drop_table('draw_config')
    # ### end Alembic commands ###
