"""drop_winner_table

Revision ID: 87739b4dc709
Revises: 
Create Date: 2025-10-04 13:56:59.358862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87739b4dc709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make all operations conditional for fresh database setups
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Drop table only if it exists
    if 'winners' in inspector.get_table_names():
        op.drop_table('winners')
    
    # Handle indexes conditionally
    table_names = inspector.get_table_names()
    
    # Handle trivia_questions_answers indexes
    if 'trivia_questions_answers' in table_names:
        indexes = [idx['name'] for idx in inspector.get_indexes('trivia_questions_answers')]
        if 'ix_user_question_answers_id' in indexes:
            op.drop_index('ix_user_question_answers_id', table_name='trivia_questions_answers')
        if 'ix_trivia_questions_answers_id' not in indexes:
            op.create_index(op.f('ix_trivia_questions_answers_id'), 'trivia_questions_answers', ['id'], unique=False)
    
    # Handle trivia_questions_daily indexes
    if 'trivia_questions_daily' in table_names:
        indexes = [idx['name'] for idx in inspector.get_indexes('trivia_questions_daily')]
        if 'ix_daily_questions_id' in indexes:
            op.drop_index('ix_daily_questions_id', table_name='trivia_questions_daily')
        if 'ix_trivia_questions_daily_id' not in indexes:
            op.create_index(op.f('ix_trivia_questions_daily_id'), 'trivia_questions_daily', ['id'], unique=False)
    
    # Handle trivia_questions_winners indexes
    if 'trivia_questions_winners' in table_names:
        indexes = [idx['name'] for idx in inspector.get_indexes('trivia_questions_winners')]
        if 'ix_trivia_draw_winners_id' in indexes:
            op.drop_index('ix_trivia_draw_winners_id', table_name='trivia_questions_winners')
        if 'ix_trivia_questions_winners_id' not in indexes:
            op.create_index(op.f('ix_trivia_questions_winners_id'), 'trivia_questions_winners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_questions_winners_id'), table_name='trivia_questions_winners')
    op.create_index('ix_trivia_draw_winners_id', 'trivia_questions_winners', ['id'], unique=False)
    op.drop_index(op.f('ix_trivia_questions_daily_id'), table_name='trivia_questions_daily')
    op.create_index('ix_daily_questions_id', 'trivia_questions_daily', ['id'], unique=False)
    op.drop_index(op.f('ix_trivia_questions_answers_id'), table_name='trivia_questions_answers')
    op.create_index('ix_user_question_answers_id', 'trivia_questions_answers', ['id'], unique=False)
    op.create_table('winners',
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount_won', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('win_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('first_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('second_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('third_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fourth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sixth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('seventh_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eighth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ninth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tenth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='winners_account_id_fkey'),
    sa.PrimaryKeyConstraint('account_id', name='winners_pkey')
    )
    # ### end Alembic commands ###
