"""drop_winner_table

Revision ID: 87739b4dc709
Revises: 
Create Date: 2025-10-04 13:56:59.358862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87739b4dc709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winners')
    op.drop_index('ix_user_question_answers_id', table_name='trivia_questions_answers')
    op.create_index(op.f('ix_trivia_questions_answers_id'), 'trivia_questions_answers', ['id'], unique=False)
    op.drop_index('ix_daily_questions_id', table_name='trivia_questions_daily')
    op.create_index(op.f('ix_trivia_questions_daily_id'), 'trivia_questions_daily', ['id'], unique=False)
    op.drop_index('ix_trivia_draw_winners_id', table_name='trivia_questions_winners')
    op.create_index(op.f('ix_trivia_questions_winners_id'), 'trivia_questions_winners', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_questions_winners_id'), table_name='trivia_questions_winners')
    op.create_index('ix_trivia_draw_winners_id', 'trivia_questions_winners', ['id'], unique=False)
    op.drop_index(op.f('ix_trivia_questions_daily_id'), table_name='trivia_questions_daily')
    op.create_index('ix_daily_questions_id', 'trivia_questions_daily', ['id'], unique=False)
    op.drop_index(op.f('ix_trivia_questions_answers_id'), table_name='trivia_questions_answers')
    op.create_index('ix_user_question_answers_id', 'trivia_questions_answers', ['id'], unique=False)
    op.create_table('winners',
    sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('amount_won', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('win_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('first_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('second_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('third_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fourth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fifth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sixth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('seventh_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eighth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ninth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tenth_prize', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], name='winners_account_id_fkey'),
    sa.PrimaryKeyConstraint('account_id', name='winners_pkey')
    )
    # ### end Alembic commands ###
