"""trivia1

Revision ID: 93165f61509c
Revises: df78c0d25fcd
Create Date: 2025-04-15 00:19:10.494533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93165f61509c'
down_revision: Union[str, None] = 'df78c0d25fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.ForeignKeyConstraint(['question_number'], ['trivia.question_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'question_number', 'date', name='unique_user_question_date')
    )
    op.create_index(op.f('ix_user_question_answers_id'), 'user_question_answers', ['id'], unique=False)
    op.add_column('daily_questions', sa.Column('correct_answer', sa.String(), nullable=True))
    op.create_unique_constraint('unique_date_question', 'daily_questions', ['date', 'question_number'])
    op.drop_constraint('daily_questions_account_id_fkey', 'daily_questions', type_='foreignkey')
    op.drop_column('daily_questions', 'answered_at')
    op.drop_column('daily_questions', 'is_correct')
    op.drop_column('daily_questions', 'account_id')
    op.drop_column('daily_questions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_questions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_questions', sa.Column('account_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('daily_questions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('daily_questions', sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('daily_questions_account_id_fkey', 'daily_questions', 'users', ['account_id'], ['account_id'])
    op.drop_constraint('unique_date_question', 'daily_questions', type_='unique')
    op.drop_column('daily_questions', 'correct_answer')
    op.drop_index(op.f('ix_user_question_answers_id'), table_name='user_question_answers')
    op.drop_table('user_question_answers')
    # ### end Alembic commands ###
