"""subscription1

Revision ID: aa484a3e08f6
Revises: d0d788191819
Create Date: 2025-04-15 22:56:03.557872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa484a3e08f6'
down_revision: Union[str, None] = 'd0d788191819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('weekly_revenue', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('streak_rewards_paid', sa.Float(), nullable=False),
    sa.Column('total_streak_rewards_paid', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date')
    )
    op.create_index(op.f('ix_company_revenue_id'), 'company_revenue', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('jan_subscribed', sa.Boolean(), nullable=False),
    sa.Column('feb_subscribed', sa.Boolean(), nullable=False),
    sa.Column('mar_subscribed', sa.Boolean(), nullable=False),
    sa.Column('apr_subscribed', sa.Boolean(), nullable=False),
    sa.Column('may_subscribed', sa.Boolean(), nullable=False),
    sa.Column('jun_subscribed', sa.Boolean(), nullable=False),
    sa.Column('jul_subscribed', sa.Boolean(), nullable=False),
    sa.Column('aug_subscribed', sa.Boolean(), nullable=False),
    sa.Column('sep_subscribed', sa.Boolean(), nullable=False),
    sa.Column('oct_subscribed', sa.Boolean(), nullable=False),
    sa.Column('nov_subscribed', sa.Boolean(), nullable=False),
    sa.Column('dec_subscribed', sa.Boolean(), nullable=False),
    sa.Column('total_payments', sa.Float(), nullable=False),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'year')
    )
    op.add_column('users', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_end_date')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_company_revenue_id'), table_name='company_revenue')
    op.drop_table('company_revenue')
    # ### end Alembic commands ###
