"""Initial migration

Revision ID: bd034d224b78
Revises: 
Create Date: 2025-03-16 21:20:27.006198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd034d224b78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liveupdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liveupdates_id'), 'liveupdates', ['id'], unique=False)
    op.create_table('trivia',
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('fill_in_answer', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('que_displayed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('question_number')
    )
    op.create_table('updates',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_updates_post_id'), 'updates', ['post_id'], unique=False)
    op.create_table('users',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('ssn', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('notification_on', sa.Boolean(), nullable=True),
    sa.Column('street_1', sa.String(), nullable=True),
    sa.Column('street_2', sa.String(), nullable=True),
    sa.Column('suite_or_apt_number', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('subscriber_number', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('subscription_flag', sa.Boolean(), nullable=True),
    sa.Column('sign_up_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chats',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_account_id', sa.Integer(), nullable=False),
    sa.Column('receiver_account_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('request_status', sa.String(), nullable=True),
    sa.Column('request_responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_account_id'], ['users.account_id'], ),
    sa.ForeignKeyConstraint(['sender_account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chats_message_id'), 'chats', ['message_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['updates.post_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('entries',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('number_of_entries', sa.Integer(), nullable=False),
    sa.Column('ques_attempted', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('payment',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_number', sa.String(), nullable=False),
    sa.Column('routing_number', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.String(), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.Column('autopayment', sa.Boolean(), nullable=True),
    sa.Column('first_name_on_card', sa.String(), nullable=True),
    sa.Column('last_name_on_card', sa.String(), nullable=True),
    sa.Column('billing_street_1', sa.String(), nullable=True),
    sa.Column('billing_street_2', sa.String(), nullable=True),
    sa.Column('billing_suite_or_apt_num', sa.String(), nullable=True),
    sa.Column('billing_city', sa.String(), nullable=True),
    sa.Column('billing_state', sa.String(), nullable=True),
    sa.Column('billing_country', sa.String(), nullable=True),
    sa.Column('billing_zip', sa.String(), nullable=True),
    sa.Column('payment_history', sa.String(), nullable=True),
    sa.Column('subscription_date', sa.DateTime(), nullable=True),
    sa.Column('six_months_subscription', sa.Boolean(), nullable=True),
    sa.Column('twelve_months_subscription', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('winners',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_won', sa.Float(), nullable=False),
    sa.Column('win_date', sa.DateTime(), nullable=False),
    sa.Column('first_prize', sa.Float(), nullable=True),
    sa.Column('second_prize', sa.Float(), nullable=True),
    sa.Column('third_prize', sa.Float(), nullable=True),
    sa.Column('fourth_prize', sa.Float(), nullable=True),
    sa.Column('fifth_prize', sa.Float(), nullable=True),
    sa.Column('sixth_prize', sa.Float(), nullable=True),
    sa.Column('seventh_prize', sa.Float(), nullable=True),
    sa.Column('eighth_prize', sa.Float(), nullable=True),
    sa.Column('ninth_prize', sa.Float(), nullable=True),
    sa.Column('tenth_prize', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('withdrawal_method', sa.String(), nullable=False),
    sa.Column('withdrawal_status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_table('winners')
    op.drop_table('payment')
    op.drop_table('entries')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_chats_message_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_updates_post_id'), table_name='updates')
    op.drop_table('updates')
    op.drop_table('trivia')
    op.drop_index(op.f('ix_liveupdates_id'), table_name='liveupdates')
    op.drop_table('liveupdates')
    # ### end Alembic commands ###
