"""auth_migration7

Revision ID: bf4a92051db7
Revises: 05ecb89850c2
Create Date: 2025-03-23 22:49:02.778933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a92051db7'
down_revision: Union[str, None] = '05ecb89850c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('question_done', sa.Boolean(), nullable=True))
    op.drop_column('trivia', 'status_flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('status_flag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('trivia', 'question_done')
    # ### end Alembic commands ###
