"""add_live_chat_tables

Revision ID: d2a824d58be2
Revises: 5613f2f8f4e9
Create Date: 2025-10-11 16:03:15.595429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a824d58be2'
down_revision: Union[str, None] = '5613f2f8f4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_sessions_id'), 'live_chat_sessions', ['id'], unique=False)
    op.create_table('live_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_messages_id'), 'live_chat_messages', ['id'], unique=False)
    op.create_table('live_chat_viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_viewers_id'), 'live_chat_viewers', ['id'], unique=False)
    op.create_table('live_chat_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['live_chat_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['live_chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_chat_likes_id'), 'live_chat_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_chat_likes_id'), table_name='live_chat_likes')
    op.drop_table('live_chat_likes')
    op.drop_index(op.f('ix_live_chat_viewers_id'), table_name='live_chat_viewers')
    op.drop_table('live_chat_viewers')
    op.drop_index(op.f('ix_live_chat_messages_id'), table_name='live_chat_messages')
    op.drop_table('live_chat_messages')
    op.drop_index(op.f('ix_live_chat_sessions_id'), table_name='live_chat_sessions')
    op.drop_table('live_chat_sessions')
    # ### end Alembic commands ###
