"""auth_migration16

Revision ID: df78c0d25fcd
Revises: d8259056e7c7
Create Date: 2025-04-14 21:23:01.924686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df78c0d25fcd'
down_revision: Union[str, None] = 'd8259056e7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_saver_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('question_reroll_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('extra_chance_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('hint_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('fifty_fifty_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('auto_answer_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('hint_used_today', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('fifty_fifty_used_today', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('auto_answer_used_today', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_answer_used_today')
    op.drop_column('users', 'fifty_fifty_used_today')
    op.drop_column('users', 'hint_used_today')
    op.drop_column('users', 'auto_answer_count')
    op.drop_column('users', 'fifty_fifty_count')
    op.drop_column('users', 'hint_count')
    op.drop_column('users', 'extra_chance_count')
    op.drop_column('users', 'question_reroll_count')
    op.drop_column('users', 'streak_saver_count')
    # ### end Alembic commands ###
