"""Change entries primary key to composite account_id and date

Revision ID: eefa37b6041f
Revises: 29c038d6d428
Create Date: 2025-04-13 11:26:36.883048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefa37b6041f'
down_revision: Union[str, None] = '29c038d6d428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_draw_config_id'), 'draw_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draw_config_id'), table_name='draw_config')
    # ### end Alembic commands ###
