"""auth_migration11

Revision ID: ef6ea108672f
Revises: 63d347dd3cce
Create Date: 2025-04-10 22:41:16.828779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6ea108672f'
down_revision: Union[str, None] = '63d347dd3cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
