"""add_hint_column_to_trivia

Revision ID: f5e6f9488c47
Revises: d2a824d58be2
Create Date: 2025-10-14 23:34:23.304696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e6f9488c47'
down_revision: Union[str, None] = 'd2a824d58be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia', sa.Column('hint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trivia', 'hint')
    # ### end Alembic commands ###
