"""auth_migration9

Revision ID: fc08843112f5
Revises: 171597d8d13f
Create Date: 2025-04-10 20:24:12.366685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc08843112f5'
down_revision: Union[str, None] = '171597d8d13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_winner_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winner_config_id'), 'winner_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_winner_config_id'), table_name='winner_config')
    op.drop_table('winner_config')
    # ### end Alembic commands ###
