name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly scan on Sundays

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Verify dependency versions
        run: |
          python verify_dependencies.py
          
      - name: Run dependency check with safety
        run: |
          pip install safety
          safety check -r requirements.txt --full-report

      - name: Run Bandit (Python security scanner)
        run: |
          pip install bandit
          bandit -r . -x "./tests/*,./venv/*" -f json -o bandit-report.json
          
      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            bandit-report.json 